package com.antivocale.app.data

import android.content.Context
import android.util.Log
import com.antivocale.app.data.TranscriptionCalibrator.CalibrationProfile
import java.math.BigDecimal
import org.json.JSONObject

/**
 * TASK-658 / GH #120: the measured-accuracy artifact
 * (`app/src/main/assets/model-accuracy.json`, regenerated by
 * `scripts/generate-accuracy-artifact.py` from `scripts/accuracy-sources.csv`).
 *
 * The maintainer's constraint: accuracy numbers never render inline in the
 * model list or picker (multilingual entries would flood the row); the
 * PerformanceStatsDialog is the one surface, one tap deeper. Rows join onto
 * the dialog's calibration profiles by (modelId, variant):
 * - built-in backends: the two calibration-key halves, i.e. the catalog id
 *   and the variant dirName ("sherpa-onnx" + "parakeet-tdt-0.6b-v3-smoothquant").
 * - external-catalog entries: modelId [EXTERNAL_MODEL_ID] and the variant is
 *   the importer-sanitized entry displayName; imported dirs carry a random
 *   6-hex suffix (ExternalModelImporter's freshTargetDir), so the match
 *   accepts the prefix form.
 *
 * Fail-open by design (the [MeasuredModelMemory.decode] style): a corrupt
 * asset decodes to an empty list and the dialog simply shows no section.
 * The numbers are reference data, never load-bearing.
 */
object ModelAccuracy {

    private const val TAG = "ModelAccuracy"
    private const val ASSET_NAME = "model-accuracy.json"

    /** modelId carried by rows about external-catalog entries (any import of the entry matches). */
    const val EXTERNAL_MODEL_ID = "external"

    data class Measurement(
        val modelId: String,
        val variant: String,
        val language: String,
        val metric: String,
        val value: Double,
        val corpus: String,
        val date: String,
    ) {
        /**
         * The measured value with its exact precision, no padding and no
         * rounding: 5.4 renders "5.4", 7.65 renders "7.65". A displayed
         * accuracy number must never differ from the measured one.
         */
        val displayValue: String
            get() = BigDecimal(value.toString()).stripTrailingZeros().toPlainString()

        /**
         * Whether this row describes the model behind a calibration key's
         * halves. Built-ins match exactly; external rows match the dirName
         * with or without the importer's random 6-hex suffix.
         */
        /**
         * The importer appends exactly "-" + 6 hex chars to the sanitized
         * entry name (freshTargetDir); a plain startsWith would cross-match
         * catalog names that are prefixes of each other ("Foo" vs "Foo-2").
         */
        private fun isSuffixedDirName(dirName: String): Boolean {
            if (!dirName.startsWith("$variant-")) return false
            val suffix = dirName.removePrefix("$variant-")
            return suffix.length == 6 && suffix.all { it.isDigit() || it in 'a'..'f' }
        }

        fun matches(backendId: String, dirName: String): Boolean = when {
            modelId == EXTERNAL_MODEL_ID ->
                backendId.startsWith(ExternalModelRecord.BACKEND_ID_PREFIX) &&
                    (dirName == variant || isSuffixedDirName(dirName))
            else -> modelId == backendId && variant == dirName
        }
    }

    /** Decodes the asset; corrupt input yields an empty list (fail-open). */
    fun decode(json: String?): List<Measurement> {
        if (json.isNullOrBlank()) return emptyList()
        return runCatching {
            val rows = JSONObject(json).optJSONArray("measurements")
                ?: return@runCatching emptyList<Measurement>()
            val out = ArrayList<Measurement>(rows.length())
            for (i in 0 until rows.length()) {
                val o = rows.optJSONObject(i) ?: continue
                // A row without identity fields or a numeric value can match
                // nothing; it is skipped rather than failing the whole asset.
                val modelId = o.optString("modelId")
                val variant = o.optString("variant")
                val language = o.optString("language")
                val metric = o.optString("metric")
                val value = o.optDouble("value", Double.NaN)
                if (modelId.isBlank() || variant.isBlank() ||
                    language.isBlank() || metric.isBlank() || value.isNaN()
                ) continue
                out.add(
                    Measurement(
                        modelId = modelId,
                        variant = variant,
                        language = language,
                        metric = metric,
                        value = value,
                        corpus = o.optString("corpus"),
                        date = o.optString("date"),
                    )
                )
            }
            out
        }.getOrDefault(emptyList())
    }

    /** Fail-open read of the bundled asset; a corrupt asset is logged once per process. */
    fun load(context: Context): List<Measurement> {
        val text = runCatching {
            context.assets.open(ASSET_NAME).bufferedReader().use { it.readText() }
        }.getOrElse {
            warnOnce("asset $ASSET_NAME unreadable; accuracy section hidden: $it")
            return emptyList()
        }
        return decode(text).also {
            if (it.isEmpty()) warnOnce("asset $ASSET_NAME decoded empty (corrupt?); accuracy section hidden")
        }
    }

    /**
     * Joins measurements onto the dialog's profiles (in profile order):
     * each entry carries the profile and its measured rows. Profiles whose
     * (modelId, variant) has no measurement are absent, which is the honest
     * rendering the task demands: nothing invented, nothing borrowed from a
     * different corpus.
     */
    fun rowsFor(
        profiles: List<CalibrationProfile>,
        measurements: List<Measurement>,
    ): List<Pair<CalibrationProfile, List<Measurement>>> =
        profiles.mapNotNull { profile ->
            val backendId = TranscriptionCalibrator.backendIdOf(profile.modelId)
            val dirName = TranscriptionCalibrator.dirNameOf(profile.modelId)
            val rows = measurements.filter { it.matches(backendId, dirName) }
            if (rows.isEmpty()) null else profile to rows
        }

    @Volatile
    private var warned = false

    private fun warnOnce(message: String) {
        if (warned) return
        warned = true
        Log.w(TAG, message)
    }
}
