package com.antivocale.app.transcription

import com.antivocale.app.data.catalog.CatalogEntry
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * TASK-413 / GH #68 defense 2: the ground-truth fixture contract.
 *
 * For every bundled entry the load path checks (skipMetadataCheck not set,
 * the same filter as BundledCatalogMetadataPolicyTest and
 * SherpaBackend.loadModel), the repo carries a fixture with the encoder's
 * ACTUAL metadata_props keys, generated by scripts/extract-metadata-fixtures.py
 * from the SHA-pinned published artifact. This test asserts
 * [SherpaBackend.requiredMetadataKeys] is a SUBSET of the fixture keys: the
 * guard must never demand what the artifact does not carry, the exact
 * condition that shipped qwen3 broken for five releases (the test of that
 * era pinned the author's assumption; these fixtures pin the artifact).
 *
 * The fixture also records the encoder's catalog sha256 pin, asserted here
 * against the live catalog: a model update that changes any pin (or drops
 * metadata from the export) fails this suite until the fixtures are
 * regenerated, which is the intended tripwire. Regeneration: the header of
 * scripts/extract-metadata-fixtures.py documents the cache layout and the
 * default pin-cache path.
 */
class MetadataFixturesContractTest {

    @Test
    fun `required metadata keys are a subset of each pinned encoder's actual keys`() {
        val problems = mutableListOf<String>()
        checkedEntries().forEach { entry ->
            val fixture = loadFixture(entry.id)
            if (fixture == null) {
                problems.add(
                    "${entry.id}: fixture missing, regenerate with " +
                        "scripts/extract-metadata-fixtures.py (its header documents the cache " +
                        "layout and the default pin-cache path)"
                )
                return@forEach
            }
            if (fixture.getString("modelType") != entry.modelType) {
                problems.add(
                    "${entry.id}: fixture modelType '${fixture.getString("modelType")}' != " +
                        "catalog '${entry.modelType}' (regenerate the fixture)"
                )
                return@forEach
            }
            // The extractor must read the same tail window the production
            // scanner does, or "regenerate" cannot fix a subset failure.
            if (fixture.getLong("scanWindowBytes") != SherpaBackend.ONNX_METADATA_SCAN_LIMIT) {
                problems.add(
                    "${entry.id}: fixture scan window ${fixture.getLong("scanWindowBytes")} != " +
                        "production ONNX_METADATA_SCAN_LIMIT " +
                        "${SherpaBackend.ONNX_METADATA_SCAN_LIMIT}; update " +
                        "SCAN_WINDOW_BYTES in scripts/extract-metadata-fixtures.py and regenerate"
                )
                return@forEach
            }
            val required = SherpaBackend.requiredMetadataKeys(entry)
            val fixtureVariantsObj = fixture.getJSONObject("variants")
            val fixtureVariants = buildSet {
                val iterator = fixtureVariantsObj.keys()
                while (iterator.hasNext()) add(iterator.next())
            }
            val catalogVariants = entry.variants.map { it.name }.toSet()
            if (fixtureVariants != catalogVariants) {
                problems.add(
                    "${entry.id}: fixture variants $fixtureVariants != catalog variants " +
                        "$catalogVariants (regenerate the fixture)"
                )
                return@forEach
            }
            entry.variants.forEach { variant ->
                val recorded = fixtureVariantsObj.getJSONObject(variant.name)
                val keysArray = recorded.getJSONArray("keys")
                val keys = buildSet {
                    for (i in 0 until keysArray.length()) add(keysArray.getString(i))
                }
                val demanding = required.filter { it !in keys }
                if (demanding.isNotEmpty()) {
                    problems.add(
                        "${entry.id}/${variant.name}: guard demands $demanding but the pinned " +
                            "encoder carries only ${keys.sorted()}; the guard would reject a " +
                            "loadable model (the GH #68 class)"
                    )
                }
                // The encoder the production loader scans: resolveRoles, not a
                // test-side matcher that could drift from it (the subset proof
                // must cover the file loadModel actually reads).
                val encoderName = SherpaBackend.resolveRoles(variant).encoder
                val pin = variant.files.firstOrNull { it.name == encoderName }?.sha256
                if (recorded.getString("encoder") != encoderName) {
                    problems.add(
                        "${entry.id}/${variant.name}: fixture encoder " +
                            "'${recorded.getString("encoder")}' != catalog role '$encoderName'"
                    )
                }
                if (pin != null && recorded.getString("sha256") != pin) {
                    problems.add(
                        "${entry.id}/${variant.name}: encoder pin changed to $pin but the " +
                            "fixture records ${recorded.getString("sha256")}; regenerate the " +
                            "fixtures together with the catalog change"
                    )
                }
            }
        }
        assertTrue(problems.joinToString("\n"), problems.isEmpty())
    }

    @Test
    fun `every checked bundled entry is covered by the contract`() {
        // The contract is only as strong as its reach: if the filter matched
        // nothing (a parsing change, a renamed flag), the suite would pass
        // vacuously. Pin the covered set to the four non-skip entries.
        assertEquals(
            setOf("sherpa-onnx", "qwen3-asr", "nemotron-streaming", "gigaam"),
            checkedEntries().map { it.id }.toSet(),
        )
    }

    /** The production filter: entries whose load path runs the metadata scan. */
    private fun checkedEntries(): List<CatalogEntry> =
        bundledCatalogEntriesForTest().filter { !it.flags.skipMetadataCheck }

    private fun loadFixture(entryId: String): JSONObject? {
        val resource = javaClass.classLoader.getResource("metadata-fixtures/$entryId.json")
            ?: return null
        return JSONObject(resource.readText())
    }
}
